# Generated by Django 4.2 on 2023-04-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_path',
            field=models.CharField(default='', max_length=255),
        ),
    ]
