# Generated by Django 4.2 on 2023-04-29 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_book_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
    ]
