# Generated by Django 4.2 on 2023-05-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_book_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('specialist', models.CharField(max_length=255)),
                ('image_path', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
