# Generated by Django 4.2 on 2023-06-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cardiac_surgery_cardiology_dermatology_ent_neurology_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoibitanBook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('author', models.CharField(max_length=255)),
                ('image_path', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
