# Generated by Django 4.2 on 2023-06-03 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_boibitanbook'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BoibitanBook',
            new_name='BOIBITAN',
        ),
    ]
