# Generated by Django 4.2 on 2023-06-03 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_boibitanbook_boibitan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CARDIAC_SURGERY',
        ),
    ]
