# Generated by Django 4.2 on 2023-06-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_delete_cardiac_surgery'),
    ]

    operations = [
        migrations.CreateModel(
            name='CARDIAC_SURGERY',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('specialist', models.CharField(max_length=255)),
                ('image_path', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
